version: "3.8"
services:
  mongo:
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: walkardev
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INIT_ROOT_PASSWORD: dev
      networks:
        - app-network
      volumes:
        - mongo-data:/data/db
      ports:
        - "27017:27017"
    
volumes:
   mongo-data:

networks:
  app-network:
    driver: bridge